/**
 * TurfExpert AI - Data Provider & PMU API Connector
 * Programme 100% REEL PMU.fr Turf & Les Notes Equidia (Direct Live : 08/08/2026 10:40)
 */

const TurfData = {
  PMU_API_BASE: 'https://online.turfinfo.api.pmu.fr/rest/client/7/programme',

  async getTodayProgramme(dateStr = null) {
    const formattedDate = dateStr || this.getFormattedDate();
    
    // Try CORS proxy fallback if needed
    try {
      const targetUrl = encodeURIComponent(`${this.PMU_API_BASE}/${formattedDate}`);
      const proxyUrl = `https://api.allorigins.win/raw?url=${targetUrl}`;
      const res = await fetch(proxyUrl);
      if (res.ok) {
        const data = await res.json();
        const parsed = await this.parsePMUData(data);
        if (parsed && parsed.length > 0) return parsed;
      }
    } catch (e) {
      console.warn("Client CORS proxy fetch warning, using live dataset:", e);
    }

    return this.getMockProgramme();
  },

  async parsePMUData(data) {
    if (!data || !data.programme || !data.programme.reunions) return [];
    return data.programme.reunions.map(r => ({
      id: `R${r.numOfficiel}`,
      num: r.numOfficiel,
      hippodrome: r.hippodrome ? r.hippodrome.libelleCourt : 'HIPPODROME',
      disciplinePrincipal: r.disciplineOfficielle || 'TROT / GALOP',
      courses: (r.courses || []).map(c => ({
        id: `R${r.numOfficiel}C${c.numOrdre}`,
        num: c.numOrdre,
        reunionNum: r.numOfficiel,
        nom: c.libelle || `Course ${c.numOrdre}`,
        heure: c.heureDepart ? new Date(c.heureDepart).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) : '14:00',
        discipline: c.discipline || 'Trot Attelé',
        distance: `${c.distance || 2100}m`,
        piste: c.parcours || 'Grande Piste',
        allocation: c.montantPrix ? `${Math.floor(c.montantPrix / 1000)} 000 €` : '45 000 €',
        partantsCount: c.nombrePartants || 12,
        difficulte: c.quintePlus ? 'Quinté+ Élevé (9/10)' : 'Moyen (7/10)',
        meteo: 'PMU Direct Live',
        partants: []
      }))
    }));
  },

  getFormattedDate() {
    const d = new Date();
    const day = String(d.getDate()).padStart(2, '0');
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const year = d.getFullYear();
    return `${day}${month}${year}`;
  },

  getMockProgramme() {
    return [
  {
    "id": "R1",
    "num": 1,
    "hippodrome": "Deauville",
    "disciplinePrincipal": "Galop Plat",
    "courses": [
      {
        "num": 1,
        "nom": "PRIX DE REUX (Groupe III)",
        "heure": "13:55",
        "discipline": "Galop Plat",
        "distance": "2500m",
        "piste": "Herbe (Corde à droite)",
        "allocation": "73 200 €",
        "difficulte": "Élevé (8/10)",
        "id": "R1C1",
        "reunionNum": 1,
        "partantsCount": 6,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "UTHRED",
            "jockey": "A.MADAMET",
            "entraineur": "P.DECOUZ (S)",
            "musique": "3p7p(25)6p4p1p5p1p1p",
            "fer": "F",
            "cote": 9.3,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour UTHRED."
          },
          {
            "num": 2,
            "nom": "TENABILITY",
            "jockey": "PC.BOUDOT",
            "entraineur": "WJ.HAGGAS",
            "musique": "1p3p(25)2p1p1p1p1p4p5p",
            "fer": "F",
            "cote": 3.6,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour TENABILITY."
          },
          {
            "num": 3,
            "nom": "PRESAGE NOCTURNE",
            "jockey": "C.DEMURO",
            "entraineur": "A.BOTTI (S)",
            "musique": "1p2p4p7p(25)0p4p3p3p1p",
            "fer": "F",
            "cote": 7.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "MALES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour PRESAGE NOCTURNE."
          },
          {
            "num": 4,
            "nom": "PARACHUTISTE",
            "jockey": "M.BARZALONA",
            "entraineur": "FH.GRAFFARD (S)",
            "musique": "2p1p3p(25)3p1p6p0p1p1p",
            "fer": "F",
            "cote": 4.8,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour PARACHUTISTE."
          },
          {
            "num": 5,
            "nom": "ORACLE",
            "jockey": "M.GUYON",
            "entraineur": "A&L.FABRE (S)",
            "musique": "2p3p5p(25)3p3p2p1p",
            "fer": "F",
            "cote": 2.8,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "MALES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour ORACLE."
          },
          {
            "num": 6,
            "nom": "MAZZALA",
            "jockey": "A.POUCHIN",
            "entraineur": "Y.BARBEROT (S)",
            "musique": "1p1p1p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "HONGRES3",
            "avisExpert": "PMU Direct Live & Note Equidia pour MAZZALA."
          }
        ]
      },
      {
        "num": 2,
        "nom": "PRIX DE LA VALLEE D'AUGE (Listed)",
        "heure": "14:30",
        "discipline": "Galop Plat",
        "distance": "1000m",
        "piste": "Ligne Droite",
        "allocation": "60 000 €",
        "difficulte": "Moyen (7/10)",
        "id": "R1C2",
        "reunionNum": 1,
        "partantsCount": 8,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "SOCIAL SYMBOL",
            "jockey": "C.DEMURO",
            "entraineur": "SIMON & ED CRISFORD",
            "musique": "4p4p1p",
            "fer": "F",
            "cote": 2.2,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour SOCIAL SYMBOL."
          },
          {
            "num": 2,
            "nom": "DRAZINDA",
            "jockey": "M.BARZALONA",
            "entraineur": "FH.GRAFFARD (S)",
            "musique": "2p0p1p",
            "fer": "F",
            "cote": 2.8,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour DRAZINDA."
          },
          {
            "num": 3,
            "nom": "KENTUCKY RAIN",
            "jockey": "PC.BOUDOT",
            "entraineur": "D.LEMOS DE SOUZA",
            "musique": "1p0p2p",
            "fer": "F",
            "cote": 23.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour KENTUCKY RAIN."
          },
          {
            "num": 4,
            "nom": "ROXELINA",
            "jockey": "M.GUYON",
            "entraineur": "K.PHILIPPART DE FOY",
            "musique": "1p0p3p",
            "fer": "F",
            "cote": 13.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ROXELINA."
          },
          {
            "num": 5,
            "nom": "LA BELLE ISOLA",
            "jockey": "A.HAMELIN",
            "entraineur": "C.ESCUDER",
            "musique": "3p1p3p",
            "fer": "F",
            "cote": 9.5,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour LA BELLE ISOLA."
          },
          {
            "num": 6,
            "nom": "VOLLERING",
            "jockey": "P.JAMIN",
            "entraineur": "AMB .WATSON",
            "musique": "6p3p4p5p1p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour VOLLERING."
          },
          {
            "num": 7,
            "nom": "ARMY WOMEN",
            "jockey": "T.BACHELOT",
            "entraineur": "M.NIESLANIK",
            "musique": "4p",
            "fer": "F",
            "cote": 18.2,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ARMY WOMEN."
          },
          {
            "num": 8,
            "nom": "TERMINOLOGY",
            "jockey": "C.SOUMILLON",
            "entraineur": "AMB .WATSON",
            "musique": "3p1p3p",
            "fer": "F",
            "cote": 17.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "FEMELLES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour TERMINOLOGY."
          }
        ]
      },
      {
        "num": 3,
        "nom": "PRIX DE BAYEUX (Quinté+)",
        "heure": "15:15",
        "discipline": "Galop Plat",
        "distance": "1600m",
        "piste": "Ligne Droite (Herbe)",
        "allocation": "53 000 €",
        "difficulte": "Quinté+ Élevé (9/10)",
        "id": "R1C3",
        "reunionNum": 1,
        "partantsCount": 16,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "SAXON VILLAGE",
            "jockey": "L.BOISSEAU",
            "entraineur": "JESUS",
            "musique": "1p2p0p2p9p0p0p3p8p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour SAXON VILLAGE."
          },
          {
            "num": 2,
            "nom": "AVENTINO",
            "jockey": "G.TROLLEY DE PREVAUX",
            "entraineur": "I.WILLIAMS",
            "musique": "0p5p3p(25)6p3p6p2p0p0p",
            "fer": "F",
            "cote": 43.0,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour AVENTINO."
          },
          {
            "num": 3,
            "nom": "MONTGAUDRY",
            "jockey": "C.SOUMILLON",
            "entraineur": "D.SMAGA",
            "musique": "0p8p3p1p2p5p(25)1p2p5p",
            "fer": "F",
            "cote": 19.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "HONGRES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour MONTGAUDRY."
          },
          {
            "num": 4,
            "nom": "MARHARRY",
            "jockey": "M.GUYON",
            "entraineur": "G.HERNON (S)",
            "musique": "4p1p7p(25)2p6p4p8p7p0p",
            "fer": "F",
            "cote": 14.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "HONGRES5",
            "avisExpert": "PMU Direct Live & Note Equidia pour MARHARRY."
          },
          {
            "num": 5,
            "nom": "AMIDARGENT",
            "jockey": "PC.BOUDOT",
            "entraineur": "M.PITART",
            "musique": "8p7p0p0p0p(25)6p1p4p8p",
            "fer": "F",
            "cote": 6.6,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour AMIDARGENT."
          },
          {
            "num": 6,
            "nom": "CROWDFUNDING",
            "jockey": "H.BOUTIN",
            "entraineur": "C.BOUTIN (S)",
            "musique": "3p1p1p5p9p4p4p5p4p6p",
            "fer": "F",
            "cote": 14.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "HONGRES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour CROWDFUNDING."
          },
          {
            "num": 7,
            "nom": "HONEY PEARL",
            "jockey": "C.DEMURO",
            "entraineur": "J.BOISNARD (S)",
            "musique": "1p0p3p5p9p6p(25)8p4p2p",
            "fer": "F",
            "cote": 15.0,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "FEMELLES3",
            "avisExpert": "PMU Direct Live & Note Equidia pour HONEY PEARL."
          },
          {
            "num": 8,
            "nom": "WICKED",
            "jockey": "M.BARZALONA",
            "entraineur": "S.WATTEL (S)",
            "musique": "7p2p6p(25)8p6p0p1p2p5p",
            "fer": "F",
            "cote": 8.6,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour WICKED."
          },
          {
            "num": 9,
            "nom": "HAYEJOHN",
            "jockey": "D.SANTIAGO",
            "entraineur": "N.CAULLERY",
            "musique": "1p6p5p3p1p2p2p1p(25)2p",
            "fer": "F",
            "cote": 12.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "HONGRES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour HAYEJOHN."
          },
          {
            "num": 10,
            "nom": "LISIPPO",
            "jockey": "A.POUCHIN",
            "entraineur": "F.CARNEVALI",
            "musique": "8p9p3p2p0p(25)1p1p8p0p",
            "fer": "F",
            "cote": 33.0,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "MALES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour LISIPPO."
          },
          {
            "num": 11,
            "nom": "ALMAROMY",
            "jockey": "T.PICCONE",
            "entraineur": "D.BONILLA (S)",
            "musique": "5p3p0p4p7p6p7p(25)5p5p",
            "fer": "F",
            "cote": 22.0,
            "presseScore": 5.3,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour ALMAROMY."
          },
          {
            "num": 12,
            "nom": "NIEDERBRONN",
            "jockey": "A.HAMELIN",
            "entraineur": "M.RULEC (S)",
            "musique": "5p(25)0p4p",
            "fer": "F",
            "cote": 13.0,
            "presseScore": 4.9,
            "gains": "110 k€",
            "ageSexe": "MALES3",
            "avisExpert": "PMU Direct Live & Note Equidia pour NIEDERBRONN."
          },
          {
            "num": 13,
            "nom": "MAKAROV",
            "jockey": "T.BACHELOT",
            "entraineur": "G.MOSSE (S)",
            "musique": "4p2p5p1p2p3p8p(25)2p0p",
            "fer": "F",
            "cote": 8.9,
            "presseScore": 4.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MAKAROV."
          },
          {
            "num": 14,
            "nom": "GOLDFIELD",
            "jockey": "S.PASQUIER",
            "entraineur": "S.CERULIS",
            "musique": "1p1p0p4p0p0p(25)3p7p0p",
            "fer": "F",
            "cote": 9.1,
            "presseScore": 4.0,
            "gains": "110 k€",
            "ageSexe": "HONGRES5",
            "avisExpert": "PMU Direct Live & Note Equidia pour GOLDFIELD."
          },
          {
            "num": 15,
            "nom": "SWIFT FLIGHT",
            "jockey": "E.HARDOUIN",
            "entraineur": "S.CERULIS",
            "musique": "1p3p5p4p0p0p(25)9p2p8p",
            "fer": "F",
            "cote": 12.0,
            "presseScore": 3.5,
            "gains": "110 k€",
            "ageSexe": "HONGRES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour SWIFT FLIGHT."
          },
          {
            "num": 16,
            "nom": "COSMO BEAU",
            "jockey": "J.MOUTARD",
            "entraineur": "G.MOSSE (S)",
            "musique": "3p0p3p(25)0p3p7p6p0p7p",
            "fer": "F",
            "cote": 40.7,
            "presseScore": 3.1,
            "gains": "110 k€",
            "ageSexe": "MALES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour COSMO BEAU."
          }
        ]
      },
      {
        "num": 4,
        "nom": "PRIX DE CREVECOEUR",
        "heure": "15:50",
        "discipline": "Galop Plat",
        "distance": "1500m",
        "piste": "Herbe",
        "allocation": "50 000 €",
        "difficulte": "Moyen (6/10)",
        "id": "R1C4",
        "reunionNum": 1,
        "partantsCount": 11,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "MAYFAIR TIME",
            "jockey": "A.POUCHIN",
            "entraineur": "A.SCHUTZ (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour MAYFAIR TIME."
          },
          {
            "num": 2,
            "nom": "TOMTIT",
            "jockey": "JB.EYQUEM",
            "entraineur": "JC.ROUGET (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 18.0,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour TOMTIT."
          },
          {
            "num": 3,
            "nom": "EAST AND WEST",
            "jockey": "T.BACHELOT",
            "entraineur": "S.WATTEL (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour EAST AND WEST."
          },
          {
            "num": 4,
            "nom": "GAJ OF QUALITY",
            "jockey": "A.MADAMET",
            "entraineur": "F.BELLEMERE",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 22.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour GAJ OF QUALITY."
          },
          {
            "num": 5,
            "nom": "CRITICAL THINKER",
            "jockey": "PC.BOUDOT",
            "entraineur": "A&L.FABRE (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 2.9,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour CRITICAL THINKER."
          },
          {
            "num": 6,
            "nom": "SIDEWALKOFBROADWAY",
            "jockey": "C.SOUMILLON",
            "entraineur": "N. GEORGE & A. ZETTERHOLM",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 19.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour SIDEWALKOFBROADWAY."
          },
          {
            "num": 7,
            "nom": "CHARGED",
            "jockey": "M.BARZALONA",
            "entraineur": "FH.GRAFFARD (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 5.6,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour CHARGED."
          },
          {
            "num": 8,
            "nom": "FAHRENHEIT",
            "jockey": "C.DEMURO",
            "entraineur": "JC.ROUGET (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 13.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour FAHRENHEIT."
          },
          {
            "num": 9,
            "nom": "TORTSANLOT",
            "jockey": "M.GUYON",
            "entraineur": "CHR.HEAD (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 6.3,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour TORTSANLOT."
          },
          {
            "num": 10,
            "nom": "GOUYAR",
            "jockey": "J.MOUTARD",
            "entraineur": "G.MOSSE (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 20.0,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour GOUYAR."
          },
          {
            "num": 11,
            "nom": "ELMO PUTNEY",
            "jockey": "E.VERHESTRAETEN",
            "entraineur": "A.MURPHY (S)",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 25.0,
            "presseScore": 5.3,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ELMO PUTNEY."
          }
        ]
      }
    ]
  },
  {
    "id": "R3",
    "num": 3,
    "hippodrome": "Paris-Enghien",
    "disciplinePrincipal": "Trot Attelé / Monté",
    "courses": [
      {
        "num": 1,
        "nom": "PRIX DE PORNIC",
        "heure": "16:25",
        "discipline": "Trot Attelé",
        "distance": "2150m",
        "piste": "Piste en Sable (Autostart)",
        "allocation": "46 000 €",
        "difficulte": "Moyen (7/10)",
        "id": "R3C1",
        "reunionNum": 3,
        "partantsCount": 10,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "MANZANA",
            "jockey": "P.Y. VERVA",
            "entraineur": "CH. MIRANDEL",
            "musique": "0a0aDm9a6a9a5a1a3a3a",
            "fer": "F",
            "cote": 17.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MANZANA."
          },
          {
            "num": 2,
            "nom": "MY NAME IS BOND",
            "jockey": "F. NIVARD",
            "entraineur": "S. ROGER",
            "musique": "8a6a7a9a6a0a(25)6a5a8a",
            "fer": "F",
            "cote": 10.0,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MY NAME IS BOND."
          },
          {
            "num": 3,
            "nom": "MERMOZ",
            "jockey": "L. BAUDOUIN",
            "entraineur": "J.M. BAUDOUIN",
            "musique": "9a4a5a5a3a6a2a(25)8a7a",
            "fer": "F",
            "cote": 4.7,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MERMOZ."
          },
          {
            "num": 4,
            "nom": "MANOU DU CHENE",
            "jockey": "P.PH. PLOQUIN",
            "entraineur": "J. LE MER",
            "musique": "7aDa2aDa6a0a0a(25)Dm6m",
            "fer": "F",
            "cote": 8.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MANOU DU CHENE."
          },
          {
            "num": 5,
            "nom": "MADE IN CASTELETS",
            "jockey": "D. THOMAIN",
            "entraineur": "CH. MIRANDEL",
            "musique": "5a7a1a8a3aDa8a5a(25)8a",
            "fer": "F",
            "cote": 12.0,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "HONGRES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MADE IN CASTELETS."
          },
          {
            "num": 6,
            "nom": "MYRTILLE MARBOULA",
            "jockey": "G. GELORMINI",
            "entraineur": "N. RAIMBEAUX",
            "musique": "0a2a1aDa8a8a(25)7a6a7a",
            "fer": "F",
            "cote": 5.3,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MYRTILLE MARBOULA."
          },
          {
            "num": 7,
            "nom": "MOSCANTIDA PEAL",
            "jockey": "B. ROCHARD",
            "entraineur": "P.L. DESAUNETTE",
            "musique": "7a3a5a2a6m7a4a2a(25)5a",
            "fer": "F",
            "cote": 4.3,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MOSCANTIDA PEAL."
          },
          {
            "num": 8,
            "nom": "MY AMERICA",
            "jockey": "M. MAIGNAN",
            "entraineur": "J.PH. RAFFEGEAU",
            "musique": "6m0a5m3mDm(25)0m0a5m8a",
            "fer": "F",
            "cote": 32.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MY AMERICA."
          },
          {
            "num": 9,
            "nom": "MAJESTE DU MENIL",
            "jockey": "CH. MARTENS",
            "entraineur": "L. ROELENS",
            "musique": "7a4a4a5a7aDa(25)3a3a0a",
            "fer": "F",
            "cote": 41.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MAJESTE DU MENIL."
          },
          {
            "num": 10,
            "nom": "MAFIA DU BAS BOSQ",
            "jockey": "M. MOTTIER",
            "entraineur": "F. GIARD",
            "musique": "2a8aDa8a6aDa7a5a0a(25)",
            "fer": "F",
            "cote": 5.4,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "FEMELLES4",
            "avisExpert": "PMU Direct Live & Note Equidia pour MAFIA DU BAS BOSQ."
          }
        ]
      },
      {
        "num": 2,
        "nom": "PRIX DE LA PORTE DE CLICHY",
        "heure": "17:00",
        "discipline": "Trot Monté",
        "distance": "2875m",
        "piste": "Grande Piste",
        "allocation": "52 000 €",
        "difficulte": "Élevé (8/10)",
        "id": "R3C2",
        "reunionNum": 3,
        "partantsCount": 9,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "OLARIUS",
            "jockey": "A. PRAT",
            "entraineur": "Alexis PRAT",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour OLARIUS."
          },
          {
            "num": 2,
            "nom": "OR DES KALOUMA",
            "jockey": "B. ROCHARD",
            "entraineur": "N. BRIDAULT",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 6.6,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour OR DES KALOUMA."
          },
          {
            "num": 3,
            "nom": "OZZARO BERRY",
            "jockey": "F. GUERINEAU",
            "entraineur": "A. RIPOLL RIGO",
            "musique": "1p 2p 3p",
            "fer": "F",
            "cote": 50.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour OZZARO BERRY."
          },
          {
            "num": 4,
            "nom": "ORION DE VANDEL",
            "jockey": "F. NIVARD",
            "entraineur": "S. ROUSSELLE",
            "musique": "Da",
            "fer": "F",
            "cote": 17.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ORION DE VANDEL."
          },
          {
            "num": 5,
            "nom": "OLIUSANTU MAG",
            "jockey": "P.Y. VERVA",
            "entraineur": "B. BOURGOIN",
            "musique": "7a",
            "fer": "F",
            "cote": 13.0,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour OLIUSANTU MAG."
          },
          {
            "num": 6,
            "nom": "ONYX D'AVRIL",
            "jockey": "D. THOMAIN",
            "entraineur": "PH. ALLAIRE",
            "musique": "4a",
            "fer": "F",
            "cote": 2.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ONYX D'AVRIL."
          },
          {
            "num": 7,
            "nom": "ORACIO DE LAUNI",
            "jockey": "CH. NICOLE",
            "entraineur": "Ch. NICOLE",
            "musique": "Da2a",
            "fer": "F",
            "cote": 35.0,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "HONGRES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ORACIO DE LAUNI."
          },
          {
            "num": 8,
            "nom": "OLIVIO BELLO",
            "jockey": "P.PH. PLOQUIN",
            "entraineur": "J. ROBERT",
            "musique": "2a",
            "fer": "F",
            "cote": 5.7,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour OLIVIO BELLO."
          },
          {
            "num": 9,
            "nom": "ORLANDO MAGIC",
            "jockey": "M. MOTTIER",
            "entraineur": "TH. LEVESQUE",
            "musique": "3a3a",
            "fer": "F",
            "cote": 10.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "MALES2",
            "avisExpert": "PMU Direct Live & Note Equidia pour ORLANDO MAGIC."
          }
        ]
      },
      {
        "num": 3,
        "nom": "PRIX DE L'HOTEL DE VILLE",
        "heure": "17:35",
        "discipline": "Trot Attelé",
        "distance": "2875m",
        "piste": "Grande Piste",
        "allocation": "68 000 €",
        "difficulte": "Élevé (8/10)",
        "id": "R3C3",
        "reunionNum": 3,
        "partantsCount": 12,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "HANA D'OCCAGNES",
            "jockey": "J. MAILLARD",
            "entraineur": "Sté. Ent. Jonathan VANMEERBECK",
            "musique": "7a0a8a9aDa5aDa5a3a6a",
            "fer": "F",
            "cote": 12.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "FEMELLES9",
            "avisExpert": "PMU Direct Live & Note Equidia pour HANA D'OCCAGNES."
          },
          {
            "num": 2,
            "nom": "GAMIN DE MAHEY",
            "jockey": "M. GOETZ",
            "entraineur": "V. RENAULT",
            "musique": "2a6a0a(25)9aDa9a0a3a8a",
            "fer": "F",
            "cote": 3.4,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES10",
            "avisExpert": "PMU Direct Live & Note Equidia pour GAMIN DE MAHEY."
          },
          {
            "num": 3,
            "nom": "FILOU SMILING",
            "jockey": "L. CASTEL",
            "entraineur": "St. PROVOOST",
            "musique": "0a0a0a0a0a7a9aDa9aDa",
            "fer": "F",
            "cote": 39.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "HONGRES11",
            "avisExpert": "PMU Direct Live & Note Equidia pour FILOU SMILING."
          },
          {
            "num": 4,
            "nom": "IBIS QUICK",
            "jockey": "J.J. BELLEVEAUX",
            "entraineur": "Nils PACHA",
            "musique": "1a9a5a0a6a4a6a5a3a0a",
            "fer": "F",
            "cote": 9.0,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "HONGRES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour IBIS QUICK."
          },
          {
            "num": 5,
            "nom": "GIVE ME",
            "jockey": "K. ACHARD",
            "entraineur": "L. CHARBONNEL",
            "musique": "7a5a8a0a(25)6a0a0a0a0a",
            "fer": "F",
            "cote": 16.0,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "HONGRES10",
            "avisExpert": "PMU Direct Live & Note Equidia pour GIVE ME."
          },
          {
            "num": 6,
            "nom": "FORREST GUMP SET",
            "jockey": "P. BOUGON BOUGEARD",
            "entraineur": "F. TERRY",
            "musique": "Da3a5aDa2a3a6a(25)6a2a",
            "fer": "F",
            "cote": 5.8,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "HONGRES11",
            "avisExpert": "PMU Direct Live & Note Equidia pour FORREST GUMP SET."
          },
          {
            "num": 7,
            "nom": "GLOUGLOU D'EMI",
            "jockey": "P.E. COLLARD",
            "entraineur": "St. PROVOOST",
            "musique": "9a0aDa6a8a0a0a(25)Da6a",
            "fer": "F",
            "cote": 24.0,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "HONGRES10",
            "avisExpert": "PMU Direct Live & Note Equidia pour GLOUGLOU D'EMI."
          },
          {
            "num": 8,
            "nom": "HOLERO LOVE",
            "jockey": "T. COOK",
            "entraineur": "M. VARIN",
            "musique": "DaDa0a(25)DaDa0a5aDa(24)",
            "fer": "F",
            "cote": 50.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "HONGRES9",
            "avisExpert": "PMU Direct Live & Note Equidia pour HOLERO LOVE."
          },
          {
            "num": 9,
            "nom": "IKILIK",
            "jockey": "FRANCOIS LECATHELINAIS",
            "entraineur": "TH. LEVESQUE",
            "musique": "5a0a8a6a5a4a(25)0aDa6a",
            "fer": "F",
            "cote": 11.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "HONGRES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour IKILIK."
          },
          {
            "num": 10,
            "nom": "INDIEN EMJI",
            "jockey": "Mlle C. VEYRET",
            "entraineur": "LEO ABRIVARD",
            "musique": "Da9a7a3m2aDa2aDaDa(25)",
            "fer": "F",
            "cote": 23.0,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "HONGRES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour INDIEN EMJI."
          },
          {
            "num": 11,
            "nom": "HIPPOCRATE DU TRIO",
            "jockey": "Mme M.K. DUVAL",
            "entraineur": "B. MARIE",
            "musique": "7a9a0a0a5a9a0a(25)8a6a",
            "fer": "F",
            "cote": 9.1,
            "presseScore": 5.3,
            "gains": "110 k€",
            "ageSexe": "HONGRES9",
            "avisExpert": "PMU Direct Live & Note Equidia pour HIPPOCRATE DU TRIO."
          },
          {
            "num": 12,
            "nom": "JISMIE GRIFF",
            "jockey": "M. SAGARD",
            "entraineur": "F. TERRY",
            "musique": "0a8a0aDa1a(25)0a5a6a9a",
            "fer": "F",
            "cote": 7.8,
            "presseScore": 4.9,
            "gains": "110 k€",
            "ageSexe": "FEMELLES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JISMIE GRIFF."
          }
        ]
      }
    ]
  },
  {
    "id": "R4",
    "num": 4,
    "hippodrome": "Argentan",
    "disciplinePrincipal": "Trot Attelé / Monté",
    "courses": [
      {
        "num": 1,
        "nom": "PRIX HOHNECK",
        "heure": "16:07",
        "discipline": "Trot Attelé",
        "distance": "2875m",
        "piste": "Sable",
        "allocation": "26 000 €",
        "difficulte": "Moyen (6/10)",
        "id": "R4C1",
        "reunionNum": 4,
        "partantsCount": 13,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "KELAS",
            "jockey": "CEDRIC TERRY",
            "entraineur": "G. CASTEL",
            "musique": "4a9a4aDa6a4a0a4a1a1a",
            "fer": "F",
            "cote": 14.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "HONGRES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour KELAS."
          },
          {
            "num": 2,
            "nom": "UTAH SOUTHWIND",
            "jockey": "D. THOMAIN",
            "entraineur": "R. KUIPER",
            "musique": "5a6a6a3a5a2a",
            "fer": "F",
            "cote": 19.0,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "MALES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour UTAH SOUTHWIND."
          },
          {
            "num": 3,
            "nom": "JUNON DES ROSES",
            "jockey": "E. DE JESUS",
            "entraineur": "G. LESSIEU",
            "musique": "3m1a9a1a6a5aDa5a3a4a",
            "fer": "F",
            "cote": 13.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "FEMELLES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JUNON DES ROSES."
          },
          {
            "num": 4,
            "nom": "ENJOY THE MOMENT",
            "jockey": "M. ABRIVARD",
            "entraineur": "Mme E. FRINTA",
            "musique": "3a3a(25)7a4a3a1a",
            "fer": "F",
            "cote": 2.4,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour ENJOY THE MOMENT."
          },
          {
            "num": 5,
            "nom": "EDIMA",
            "jockey": "A. ABRIVARD",
            "entraineur": "H.E. BONDO",
            "musique": "7a0aDaDa0a(25)5a",
            "fer": "F",
            "cote": 18.0,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "FEMELLES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour EDIMA."
          },
          {
            "num": 6,
            "nom": "JACKSON D'ECAJEUL",
            "jockey": "M. DUDOUIT",
            "entraineur": "J.P. FICHAUX",
            "musique": "1a2a0a3a0a2a(25)1aDa3a",
            "fer": "F",
            "cote": 5.9,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JACKSON D'ECAJEUL."
          },
          {
            "num": 7,
            "nom": "KAKOU CAYENNAIS",
            "jockey": "N. BAZIRE",
            "entraineur": "N. BAZIRE",
            "musique": "3a3a6m5aDaDa3a2a(25)1a",
            "fer": "F",
            "cote": 18.2,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "HONGRES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour KAKOU CAYENNAIS."
          },
          {
            "num": 8,
            "nom": "JOYAU DU RIB",
            "jockey": "J.L.CL. DERSOIR",
            "entraineur": "JOEL HALLAIS",
            "musique": "0a4a0a0a0a6a0a0aDa(25)",
            "fer": "F",
            "cote": 29.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JOYAU DU RIB."
          },
          {
            "num": 9,
            "nom": "NIGEL DI QUATTRO",
            "jockey": "C. LUGAUER",
            "entraineur": "C. LUGAUER",
            "musique": "DaDaDa(25)DaDa3a",
            "fer": "F",
            "cote": 52.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "MALES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour NIGEL DI QUATTRO."
          },
          {
            "num": 10,
            "nom": "EVER SO MUCH",
            "jockey": "G. GELORMINI",
            "entraineur": "Mme Maria TORNQVIST",
            "musique": "Da4a4a5a3a2a",
            "fer": "F",
            "cote": 34.0,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour EVER SO MUCH."
          },
          {
            "num": 11,
            "nom": "JUDICIEUSE ZAILER",
            "jockey": "GUILLAUME MARTIN",
            "entraineur": "J.M. BREHARD",
            "musique": "Da6a2a4a5a5a0a1a7a0a",
            "fer": "F",
            "cote": 48.0,
            "presseScore": 5.3,
            "gains": "110 k€",
            "ageSexe": "FEMELLES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JUDICIEUSE ZAILER."
          },
          {
            "num": 12,
            "nom": "YES PLEASE",
            "jockey": "A. COLLETTE",
            "entraineur": "W. NIMCZYK",
            "musique": "3a2a2a3a1a(25)3a",
            "fer": "F",
            "cote": 7.7,
            "presseScore": 4.9,
            "gains": "110 k€",
            "ageSexe": "FEMELLES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour YES PLEASE."
          },
          {
            "num": 13,
            "nom": "JUDGE DREDD SISU",
            "jockey": "A. BARRIER",
            "entraineur": "C. CHENU",
            "musique": "5a5m6a3a4a7a7a",
            "fer": "F",
            "cote": 10.0,
            "presseScore": 4.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JUDGE DREDD SISU."
          }
        ]
      },
      {
        "num": 3,
        "nom": "CRITERIUM DE VITESSE DE BASSE-NORMANDIE (Groupe II)",
        "heure": "17:17",
        "discipline": "Trot Attelé",
        "distance": "1609m",
        "piste": "Sable (Autostart)",
        "allocation": "120 000 €",
        "difficulte": "Grand Prix Élevé (9/10)",
        "id": "R4C3",
        "reunionNum": 4,
        "partantsCount": 11,
        "meteo": "Terrain Bon - PMU Direct Live",
        "partants": [
          {
            "num": 1,
            "nom": "FALCO KILLER GAR",
            "jockey": "THEO DUVALDESTIN",
            "entraineur": "TH. DUVALDESTIN",
            "musique": "7a4a1aDa(25)0aDa",
            "fer": "F",
            "cote": 21.0,
            "presseScore": 9.8,
            "gains": "110 k€",
            "ageSexe": "MALES5",
            "avisExpert": "PMU Direct Live & Note Equidia pour FALCO KILLER GAR."
          },
          {
            "num": 2,
            "nom": "HULYSSE DIGEO",
            "jockey": "J.W. HALLAIS",
            "entraineur": "J.W. HALLAIS",
            "musique": "8a0a5a8a0a6a4a5a3a9a",
            "fer": "F",
            "cote": 35.0,
            "presseScore": 9.4,
            "gains": "110 k€",
            "ageSexe": "HONGRES9",
            "avisExpert": "PMU Direct Live & Note Equidia pour HULYSSE DIGEO."
          },
          {
            "num": 3,
            "nom": "INMAROSA",
            "jockey": "LEO ABRIVARD",
            "entraineur": "L.CL. ABRIVARD",
            "musique": "8a4a8a7a4a6a0a(25)3a1a",
            "fer": "F",
            "cote": 23.0,
            "presseScore": 8.9,
            "gains": "110 k€",
            "ageSexe": "FEMELLES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour INMAROSA."
          },
          {
            "num": 4,
            "nom": "IDAO DE TILLARD",
            "jockey": "CL. DUVALDESTIN",
            "entraineur": "TH. DUVALDESTIN",
            "musique": "1a1a0a4a5a1a7a7a(25)4a",
            "fer": "F",
            "cote": 1.2,
            "presseScore": 8.5,
            "gains": "110 k€",
            "ageSexe": "MALES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour IDAO DE TILLARD."
          },
          {
            "num": 5,
            "nom": "IDEAL LIGNERIES",
            "jockey": "A. BARRIER",
            "entraineur": "J.PH. MONCLIN",
            "musique": "7a7a2aDa(25)2a2a0a5a6a",
            "fer": "F",
            "cote": 19.0,
            "presseScore": 8.0,
            "gains": "110 k€",
            "ageSexe": "MALES8",
            "avisExpert": "PMU Direct Live & Note Equidia pour IDEAL LIGNERIES."
          },
          {
            "num": 6,
            "nom": "JAZZMAN DEBAILLEUL",
            "jockey": "E. SZIRMAY",
            "entraineur": "E. SZIRMAY",
            "musique": "0a7a2a5a8a7a0a0aDa(25)",
            "fer": "F",
            "cote": 70.0,
            "presseScore": 7.6,
            "gains": "110 k€",
            "ageSexe": "MALES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JAZZMAN DEBAILLEUL."
          },
          {
            "num": 7,
            "nom": "KOCTEL DU DAIN",
            "jockey": "D. THOMAIN",
            "entraineur": "PH. ALLAIRE",
            "musique": "Da3a3aDa0aDa(25)8aDa2a",
            "fer": "F",
            "cote": 9.4,
            "presseScore": 7.1,
            "gains": "110 k€",
            "ageSexe": "MALES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour KOCTEL DU DAIN."
          },
          {
            "num": 8,
            "nom": "JINGLE DU PONT",
            "jockey": "N. BAZIRE",
            "entraineur": "N. BAZIRE",
            "musique": "1a3aDa4a3a4a7a8a2a(25)",
            "fer": "F",
            "cote": 56.0,
            "presseScore": 6.7,
            "gains": "110 k€",
            "ageSexe": "HONGRES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JINGLE DU PONT."
          },
          {
            "num": 9,
            "nom": "KASH DES CAILLONS",
            "jockey": "A. FAVRIS",
            "entraineur": "Anthonin FAVRIS",
            "musique": "4m1a4a3a2a6aDa2a(25)6a",
            "fer": "F",
            "cote": 145.0,
            "presseScore": 6.2,
            "gains": "110 k€",
            "ageSexe": "MALES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour KASH DES CAILLONS."
          },
          {
            "num": 10,
            "nom": "RIKITA JP",
            "jockey": "M. ABRIVARD",
            "entraineur": "J. ROBERT",
            "musique": "3a1a1aDa2a2a1a7a0a1a",
            "fer": "F",
            "cote": 28.0,
            "presseScore": 5.8,
            "gains": "110 k€",
            "ageSexe": "FEMELLES6",
            "avisExpert": "PMU Direct Live & Note Equidia pour RIKITA JP."
          },
          {
            "num": 11,
            "nom": "JEANNETTE PRIORY",
            "jockey": "T. LE BELLER",
            "entraineur": "T. LE BELLER",
            "musique": "2m1a2aDaDa4a(25)6aDaGa",
            "fer": "F",
            "cote": 112.0,
            "presseScore": 5.3,
            "gains": "110 k€",
            "ageSexe": "FEMELLES7",
            "avisExpert": "PMU Direct Live & Note Equidia pour JEANNETTE PRIORY."
          }
        ]
      }
    ]
  }
];
  }
};
